require 'mail2frontmatter/version'
require 'mail2frontmatter/configuration'
require 'mail2frontmatter/watcher'
require 'mail2frontmatter/parser'
require 'mail2frontmatter/preprocessor'
require 'mail2frontmatter/writer'
require 'mail2frontmatter/committer'
